K8SPG-38 Upgrade test candidate

diff --git a/e2e-tests/upgrade/run b/e2e-tests/upgrade/run
--- a/e2e-tests/upgrade/run
+++ b/e2e-tests/upgrade/run
@@ -15,21 +15,53 @@ IMAGE_BACKREST="percona/percona-postgresql-operator:0.2.0-ppg13-pgbackrest"
 IMAGE_BACKREST_REPO="percona/percona-postgresql-operator:0.2.0-ppg13-pgbackrest-repo"
 IMAGE_PGBADGER="percona/percona-postgresql-operator:0.2.0-ppg13-pgbadger"
 
+compare_psql() {
+	local command_id="$1"
+	local command="$2"
+	local uri="$3"
+	local sslmode="$4"
+
+	local expected_result=${test_dir}/compare/${command_id}.sql
+
+	run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+		>$tmp_dir/${command_id}.sql
+	if [ ! -s "$tmp_dir/${command_id}.sql" ]; then
+		sleep 20
+		run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+			>$tmp_dir/${command_id}.sql
+	fi
+	diff -u $expected_result $tmp_dir/${command_id}.sql
+}
+
+run_psql_ssl() {
+	local command="$1"
+	local uri="$2"
+	local driver=${3:-postgres}
+	local suffix=${4:-.svc.cluster.local}
+	local client_container=$(kubectl_bin get pods --selector=name=pg-client -o 'jsonpath={.items[].metadata.name}')
+	local sslmode="$5"
+
+	kubectl_bin exec ${client_container} -- \
+		bash -c "printf '$command\n' | PGSSLMODE=$sslmode PGSSLROOTCERT=/tmp/tls/ca.crt psql -v ON_ERROR_STOP=1 -t -q $driver://$uri$suffix" || true
+}
+
 main() {
 	create_namespace $namespace
 
 	deploy_operator '' "${test_dir}/conf/0.2.0_operator.yaml"
 
 	desc 'start cluster'
-	cluster="upgrade"
+	cluster="some-name"
 	kubectl_bin apply -f $conf_dir/client.yml
 
 	spinup_pgcluster "${cluster}" "${test_dir}/conf/0.2.0_cr.yaml"
-	wait_deployment "${cluster}-repl1"
-	wait_deployment "${cluster}-repl2"
 	wait_job_completion "backrest-backup-${cluster}"
 
-	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p '[{"op":"replace","path":"/spec/pause","value":true}]'
+	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
+		'[
+			{"op":"replace","path":"/spec/pause","value":true},
+			{"op":"replace","path":"/spec/pgBouncer/size","value":0},
+		]'
 	wait_cluster_status "${cluster}" "pgcluster Shutdown"
 
 	kubectl_bin delete \
@@ -66,38 +98,64 @@ main() {
 
 	wait_cluster_consistency "${cluster}"
 	wait_deployment "${cluster}"
-	wait_deployment "${cluster}-repl1"
-	wait_deployment "${cluster}-repl2"
-
+	# wait for some significant time period. Pgbouncer pod may not be started otherwise
+	sleep 90
 	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
 		'[
-			{"op":"add","path":"/spec/backup/schedule","value":[{"name":"5min-backup","schedule":"*/5 * * * *","keep":3,"type":"full","storage":"local"}]},
+			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
+		]'
+	wait_cluster_consistency "${cluster}"
+	wait_deployment "${cluster}-pgbouncer"
+
+	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"
+
+	backup_time_interval_min=5
+	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
+		'[
+			{"op":"add","path":"/spec/backup/schedule","value":[{"name":"5min-backup","schedule":"*/'${backup_time_interval_min}' * * * *","keep":3,"type":"full","storage":"local"}]},
 			{"op":"add","path":"/spec/backup/storages","value":{"local":{"type":"local"}}}
 		]'
 	sleep 10
-	configmap_creation_time=$(kubectl_bin get configmap/${cluster}-5min-backup -o jsonpath='{.metadata.creationTimestamp}')
-	backup_target_minute=$(($(($(gdate -d${configmap_creation_time} +%M)+5))-$(($(($(gdate -d${configmap_creation_time} +%M)+5))%5))))
+	configmap_creation_time=$(kubectl_bin get configmap/${cluster}-${backup_time_interval_min}min-backup -o jsonpath='{.metadata.creationTimestamp}')
+	backup_target_minute=$(($(($(gdate -d${configmap_creation_time} +%M)+${backup_time_interval_min}))-$(($(($(gdate -d${configmap_creation_time} +%M)+${backup_time_interval_min}))%${backup_time_interval_min}))))
 	sleep_time=$(($((${backup_target_minute}-$(gdate +%M)))*60))
 	sleep ${sleep_time}
 
 	backup_job=$(kubectl_bin get jobs --selector=backrest-command=backup,pg-cluster=${cluster} | grep sch | awk '{print $1}')
 	wait_job_completion ${backup_job}
 
+	compare_psql_cmd "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}"
+
 	kubectl create secret generic ${cluster}-ssl-ca --from-file=ca.crt=${conf_dir}/ca.crt
 	kubectl create secret tls ${cluster}-ssl-keypair --cert=${conf_dir}/server.crt --key=${conf_dir}/server.key
-    kubectl_bin apply -f ${test_dir}/conf/client.yml
-    sleep 10
-    kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
-        '[
-            {"op":"add","path":"/spec/tlsOnly","value":true},
-            {"op":"add","path":"/spec/sslCA","value":'"'${cluster}-ssl-ca'"'},
-            {"op":"add","path":"/spec/sslSecretName","value":'"'${cluster}-ssl-keypair'"'},
-            {"op":"add","path":"/spec/sslReplicationSecretName","value":'"'${cluster}-ssl-keypair'"'},
-        ]'
-    sleep 180
-    wait_cluster_consistency "${cluster}"
-    compare_psql "select-1" '\c myapp \\\ SELECT * from myApp;' "some-name:some-name_pass@${cluster}-pgbouncer.${namespace}" "verify-ca"
+	kubectl_bin delete -f ${conf_dir}/client.yml
+	kubectl_bin apply -f ${test_dir}/conf/client.yml
+	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
+		'[
+			{"op":"add","path":"/spec/tlsOnly","value":true},
+			{"op":"add","path":"/spec/sslCA","value":'"'${cluster}-ssl-ca'"'},
+			{"op":"add","path":"/spec/sslSecretName","value":'"'${cluster}-ssl-keypair'"'},
+			{"op":"add","path":"/spec/sslReplicationSecretName","value":'"'${cluster}-ssl-keypair'"'},
+		]'
+	wait_cluster_consistency "${cluster}"
+	wait_deployment "${cluster}"
 
+	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
+		'[
+			{"op":"replace","path":"/spec/pgBouncer/size","value":0}
+		]'
+	sleep 130
+	wait_for_delete "deployment/${cluster}-pgbouncer"
+
+	kubectl_bin patch "perconapgcluster/${cluster}" --type json -p \
+		'[
+			{"op":"replace","path":"/spec/pgBouncer/size","value":1}
+		]'
+	wait_deployment "${cluster}-pgbouncer"
+
+	compare_psql "select-1" '\c myapp \\\ SELECT * from myApp;' "${cluster}:${cluster}_pass@${cluster}-pgbouncer.${namespace}" "verify-ca"
+
+	destroy "${namespace}"
 }
 
 main
