fix monitoring test

diff --git a/e2e-tests/tests/monitoring-pmm3/06-check-pgstatstatements-query-source.yaml b/e2e-tests/tests/monitoring-pmm3/06-check-pgstatstatements-query-source.yaml
--- a/e2e-tests/tests/monitoring-pmm3/06-check-pgstatstatements-query-source.yaml
+++ b/e2e-tests/tests/monitoring-pmm3/06-check-pgstatstatements-query-source.yaml
@@ -7,11 +7,20 @@ commands:
 
       source ../../functions
 
-      kubectl -n ${NAMESPACE} patch perconapgcluster/monitoring-pmm3 --type=merge -p '{"spec":{"pmm":{"querySource":"pgstatstatements"}}}'
+      kubectl -n ${NAMESPACE} patch perconapgcluster/monitoring --type=merge -p '{
+        "spec":{
+          "pmm":{"querySource":"pgstatstatements"},
+          "extensions": {"builtin": {"pg_stat_statements": true }}}
+        }
+      '
 
       # Wait for the pg_stat_statements extension to be created
       sleep 80
 
-      primary=$(get_pod_by_role monitoring-pmm3 primary name)
-      res=$(kubectl -n ${NAMESPACE} exec ${primary} -- bash -c 'psql -c "SELECT extname FROM pg_extension;"')
-      echo ${res} | grep -q pg_stat_statements
+      kubectl -n ${NAMESPACE} exec ${primary} -- bash -c 'psql -c "SELECT * FROM pg_extension;"'
+
+      primary=$(get_pod_by_role monitoring primary name)
+      if ! kubectl -n ${NAMESPACE} exec ${primary} -- bash -c 'psql -c "SELECT extname FROM pg_extension;"' | grep pg_stat_statements; then
+        echo "pg_stat_statements is not found in pg_extension"
+      fi
+    timeout: 360
