Make k8s version configurable

diff --git a/e2e-tests/tests/k8s-upgrade/00-create-k8s-cluster.yaml b/e2e-tests/tests/k8s-upgrade/00-create-k8s-cluster.yaml
--- a/e2e-tests/tests/k8s-upgrade/00-create-k8s-cluster.yaml
+++ b/e2e-tests/tests/k8s-upgrade/00-create-k8s-cluster.yaml
@@ -9,17 +9,23 @@ commands:
       source ../../functions
 
       name="k8s-upgrade-$RANDOM"
-      offset=1 # latest version
-      latest_version=$(get_available_k8s_versions "$offset" "${PLATFORM}" "$REGION")
-      offset=2 # second to last version
-      initial_version=$(get_available_k8s_versions "$offset" "${PLATFORM}" "$REGION")
 
-      if [[ "${PLATFORM}" != "gke" && "${PLATFORM}" != "digitalocean" ]]; then
-        echo "Unsupported platform: ${PLATFORM}"
+      if [[ "${K8S_UPGRADE_PLATFORM}" != "gke" && "${K8S_UPGRADE_PLATFORM}" != "digitalocean" ]]; then
+        echo "Unsupported platform: ${K8S_UPGRADE_PLATFORM}"
         exit 1
       fi
 
-      create_k8s_cluster "$name" "$initial_version" "${PLATFORM}" "${REGION}"
+      if [[ -n "${K8S_UPGRADE_INITIAL_VERSION}" && -z "${K8S_UPGRADE_FINAL_VERSION}" ]] ||
+        [[ -z "${K8S_UPGRADE_INITIAL_VERSION}" && -n "${K8S_UPGRADE_FINAL_VERSION}" ]]; then
+        echo "K8S_UPGRADE_INITIAL_VERSION and K8S_UPGRADE_FINAL_VERSION are both required when one is configured"
+        exit 1
+      fi
+
+      # By defautt, we will use the two most recent Kubernetes versions available for the specified platform and region
+      initial_version="${K8S_UPGRADE_INITIAL_VERSION:-$(get_available_k8s_versions 2 "${K8S_UPGRADE_PLATFORM}" "${K8S_UPGRADE_REGION}")}"
+      final_version="${K8S_UPGRADE_FINAL_VERSION:-$(get_available_k8s_versions 1 "${K8S_UPGRADE_PLATFORM}" "${K8S_UPGRADE_REGION}")}"
+
+      create_k8s_cluster "$name" "$initial_version" "${K8S_UPGRADE_PLATFORM}" "${K8S_UPGRADE_REGION}"
 
       # Saving cluster information and available versions for the next test steps
       kubectl create configmap cluster-name \
@@ -30,6 +36,6 @@ commands:
         --from-literal=version="$initial_version" \
         --namespace "${NAMESPACE}"
 
-      kubectl create configmap latest-cluster-version \
-        --from-literal=version="$latest_version" \
+      kubectl create configmap final-cluster-version \
+        --from-literal=version="$final_version" \
         --namespace "${NAMESPACE}"
