fix pmm

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -259,6 +259,7 @@ wait_for_delete() {
 }
 
 deploy_pmm_server() {
+<<<<<<< Updated upstream
 	local platform=kubernetes
 	helm uninstall -n "${NAMESPACE}" pmm || :
 	if [ ! -z "$OPENSHIFT" ]; then
@@ -287,6 +288,37 @@ deploy_pmm_server() {
 			exit 1
 		fi
 	done
+=======
+  local platform=kubernetes
+  helm uninstall -n "${NAMESPACE}" pmm || :
+  if [ ! -z "$OPENSHIFT" ]; then
+    platform=openshift
+    oc create sa pmm-server -n "${NAMESPACE}"
+    oc adm policy add-scc-to-user privileged -z pmm-server -n "${NAMESPACE}"
+    if [ -n "$OPERATOR_NS" ]; then
+      timeout 30 oc delete clusterrolebinding $(kubectl get clusterrolebinding | grep 'pmm-pg-operator-' | awk '{print $1}') || :
+      oc create clusterrolebinding pmm-pg-operator-cluster-wide --clusterrole=percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+      oc patch clusterrole/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' ${OPERATOR_NS:+-n $OPERATOR_NS}
+    else
+      oc create rolebinding pmm-pg-operator-namespace-only --role percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+      oc patch role/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' -n "${NAMESPACE}"
+    fi
+    retry 10 60 helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform --set sa=pmm-server --set supresshttp2=false https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
+  else
+    helm install monitoring -n "${NAMESPACE}" --set imageTag=${IMAGE_PMM_SERVER#*:} --set service.type="LoadBalancer" \
+		--set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform="${platform}" "https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz"
+  fi
+  SERVICE="postgres"
+  until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
+    echo "Retry $retry"
+    sleep 5
+    let retry+=1
+    if [ $retry -ge 20 ]; then
+      echo "Max retry count $retry reached. Pmm-server can't start"
+      exit 1
+    fi
+  done
+>>>>>>> Stashed changes
 }
 
 generate_pmm_api_key() {
@@ -357,6 +389,7 @@ deploy_chaos_mesh() {
 
 	helm repo add chaos-mesh https://charts.chaos-mesh.org
 	helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=${NAMESPACE} --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --set dashboard.create=false --version 2.5.1
+	oc adm policy add-scc-to-user privileged -z chaos-daemon --namespace=${NAMESPACE}
 	sleep 10
 }
 
