update tests

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -5,11 +5,33 @@ ROOT_REPO=${ROOT_REPO:-$(realpath ../../..)}
 source "${ROOT_REPO}/e2e-tests/vars.sh"
 test_name=$(basename "$(pwd)")
 
+if oc get projects; then
+	# Guessing Openshift version from master node API version
+	case "$(oc get nodes --no-headers=true | grep master | head -n1 | grep -Eo 'v[0-9]+\.[0-9]+')" in
+		"v1.11") OPENSHIFT=3.11 ;;
+		*) OPENSHIFT=4 ;;
+	esac
+fi
+
 create_namespace() {
 	local namespace=$1
-	if [[ ${CLEAN_NAMESPACE} == 1 ]]; then
-		kubectl delete namespace $namespace --ignore-not-found || :
-		kubectl wait --for=delete namespace "$namespace" || :
+  if [[ ${CLEAN_NAMESPACE} == 1 ]]; then
+    if [ -n "$OPENSHIFT" ]; then
+      if [ -n "$OPERATOR_NS" -a $(oc get project "$OPERATOR_NS" -o json | jq -r '.metadata.name') ]; then
+        oc delete --grace-period=0 --force=true project "$namespace" && sleep 120 || :
+      else
+        oc delete project "$namespace" && sleep 40 || :
+      fi
+      wait_for_delete "project/$namespace"
+
+      desc "create namespace $namespace"
+      oc new-project "$namespace"
+      oc project "$namespace"
+      oc adm policy add-scc-to-user hostaccess -z default || :
+    else:
+      kubectl delete namespace $namespace --ignore-not-found || :
+		  kubectl wait --for=delete namespace "$namespace" || :
+    fi
 	fi
 
 	kubectl create namespace $namespace
@@ -74,7 +96,6 @@ deploy_client() {
 
 get_cr() {
 	local name_suffix=$1
-
 	yq eval '
 		'$(printf .metadata.name="%s" \"${test_name}\")'
 		| .metadata.labels={"e2e":"'${test_name}'"}
@@ -238,10 +259,34 @@ wait_for_delete() {
 }
 
 deploy_pmm_server() {
-	local platform=kubernetes
-	helm uninstall -n "${NAMESPACE}" pmm || :
-	helm install monitoring -n "${NAMESPACE}" --set imageTag=${IMAGE_PMM_SERVER#*:} --set service.type="LoadBalancer" \
-		--set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform="${platform}" "https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz"
+  local platform=kubernetes
+  helm uninstall -n "${NAMESPACE}" pmm || :
+  if [ ! -z "$OPENSHIFT" ]; then
+    platform=openshift
+    oc create sa pmm-server -n "${NAMESPACE}"
+    oc adm policy add-scc-to-user privileged -z pmm-server -n "${NAMESPACE}"
+    if [ -n "$OPERATOR_NS" ]; then
+      timeout 30 oc delete clusterrolebinding $(kubectl get clusterrolebinding | grep 'pmm-pg-operator-' | awk '{print $1}') || :
+      oc create clusterrolebinding pmm-pg-operator-cluster-wide --clusterrole=percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+      oc patch clusterrole/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' ${OPERATOR_NS:+-n $OPERATOR_NS}
+    else
+      oc create rolebinding pmm-pg-operator-namespace-only --role percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+      oc patch role/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' -n "${NAMESPACE}"
+    fi
+    retry 10 60 helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform --set sa=pmm-server --set supresshttp2=false https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
+  else
+    helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
+  fi
+  SERVICE="postgres"
+  until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
+    echo "Retry $retry"
+    sleep 5
+    let retry+=1
+    if [ $retry -ge 20 ]; then
+      echo "Max retry count $retry reached. Pmm-server can't start"
+      exit 1
+    fi
+  done
 }
 
 generate_pmm_api_key() {
@@ -323,7 +368,7 @@ destroy_chaos_mesh() {
 		helm uninstall chaos-mesh --namespace ${chaos_mesh_ns} || :
 	fi
 	timeout 30 kubectl delete crd $(kubectl get crd | grep 'chaos-mesh.org' | awk '{print $1}') || :
-	timeout 30 kubectl delete clusterrolebinding $(kubectl get clusterrolebinding | grep 'chaos-mesh' | awk '{print $1}') || :
+	timeout 30 kubectl  delete clusterrolebinding $(kubectl get clusterrolebinding -n {NAMESPACE}| grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete clusterrole $(kubectl get clusterrole | grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete MutatingWebhookConfiguration $(kubectl get MutatingWebhookConfiguration | grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete ValidatingWebhookConfiguration $(kubectl get ValidatingWebhookConfiguration | grep 'chaos-mesh' | awk '{print $1}') || :
@@ -465,4 +510,20 @@ check_passwords_leak() {
 		pods=$(kubectl -n "${OPERATOR_NS}" get pods -o name | awk -F "/" '{print $2}')
 		collect_logs $OPERATOR_NS
 	fi
+}
+
+retry() {
+	local max=$1
+	local delay=$2
+	shift 2 # cut delay and max args
+	local n=1
+
+	until "$@"; do
+		if [[ $n -ge $max ]]; then
+			echo "The command '$@' has failed after $n attempts."
+			exit 1
+		fi
+		((n++))
+		sleep $delay
+	done
 }
