K8SPG-207 Backup/restore via self-signed tls test case

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -124,7 +124,7 @@ create_namespace() {
 deploy_cert_manager() {
 	kubectl_bin create namespace cert-manager || :
 	kubectl_bin label namespace cert-manager certmanager.k8s.io/disable-validation=true || :
-	kubectl_bin apply -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml --validate=false || : 2>/dev/null
+	kubectl_bin apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.0.4/cert-manager.yaml --validate=false || : 2>/dev/null
 	sleep 30
 }
 
@@ -205,15 +205,53 @@ deploy_operator() {
 	wait_pod $(get_operator_pod) ${OPERATOR_NS}
 }
 
-deploy_miniogw() {
-	local gsc_projectid=${1:-"cloud-dev-112233"}
-	kubectl_bin apply -f $conf_dir/cloud-secret-minio-gw.yml \
-		-f $src_dir/deploy/backup/minio-gw-tls.yaml
+retry() {
+	local max=$1
+	local delay=$2
+	shift 2 # cut delay and max args
+	local n=1
 
-	yq w -d0 --style=single $src_dir/deploy/backup/minio-gw.yaml 'spec.template.spec.containers[0].args[4]' "${gsc_projectid}" \
-		| kubectl_bin apply -f -
+	until "$@"; do
+		if [[ $n -ge $max ]]; then
+			echo "The command '$@' has failed after $n attempts."
+			exit 1
+		fi
+		((n++))
+		sleep $delay
+	done
+}
 
-	wait_pod "$(kubectl_bin get pod --selector=app=minio-gw -o 'jsonpath={.items[].metadata.name}')"
+deploy_minio() {
+	desc 'install Minio'
+	kubectl_bin apply -f $src_dir/deploy/backup/minio-gw-tls.yaml
+	helm uninstall minio-service || :
+	helm repo remove minio || :
+	helm repo add minio https://helm.min.io/
+	# kubectl_bin delete pvc minio-service --force
+	retry 10 60 helm install minio-service \
+		--version 8.0.5 \
+		--set tls.enabled=true \
+		--set accessKey=some-access-key \
+		--set secretKey=some-secret-key \
+		--set service.type=ClusterIP \
+		--set configPathmc=/tmp/.minio/ \
+		--set persistence.size=2G \
+		--set environment.MINIO_REGION=us-east-1 \
+		--set environment.MINIO_HTTP_TRACE=/tmp/trace.log \
+		--set securityContext.enabled=false \
+		--set tls.certSecret=minio-gw-tls \
+		--set tls.publicCrt=tls.crt \
+		--set tls.privateKey=tls.key \
+		--set buckets[0].name=${BUCKET} \
+		--set buckets[0].policy=public \
+		minio/minio
+	MINIO_POD=$(kubectl_bin get pods --selector=release=minio-service -o 'jsonpath={.items[].metadata.name}')
+	wait_pod $MINIO_POD
+}
+
+destroy_minio() {
+	desc 'destroy Minio'
+	helm uninstall minio-service
 }
 
 get_operator_pod() {
@@ -420,6 +458,16 @@ apply_cluster() {
 				| yq w - 'spec.backup.repoPath' "/backrestrepo/${backup//'gcs+'/}-backrest-shared-repo" \
 				| yq w - 'spec.standby' true \
 				| yq d - 'spec.pgBouncer' \
+					>"${tmp_dir}/cr.backup.yaml"
+			mv "${tmp_dir}/cr.backup.yaml" "${tmp_dir}/cr.yaml"
+			;;
+		'minio')
+			yq w "${tmp_dir}/cr.yaml" 'spec.backup.storages[my-s3].bucket' ${BUCKET} \
+				| yq w - 'spec.backup.storages[my-s3].type' 's3' \
+				| yq w - 'spec.backup.storages[my-s3].endpointUrl' 'minio-service:9000' \
+				| yq w - 'spec.backup.storages[my-s3].region' 'us-east-1' \
+				| yq w - 'spec.backup.storages[my-s3].uriStyle' 'path' \
+				| yq w - 'spec.backup.storages[my-s3].verifyTLS' false \
 					>"${tmp_dir}/cr.backup.yaml"
 			mv "${tmp_dir}/cr.backup.yaml" "${tmp_dir}/cr.yaml"
 			;;
