K8SPG-38 Linter and jenkins suggestions

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -663,6 +663,36 @@ compare_psql_cmd() {
 	diff -u $expected_result $tmp_dir/${command_id}.sql
 }
 
+compare_psql() {
+	local command_id="$1"
+	local command="$2"
+	local uri="$3"
+	local sslmode="$4"
+
+	local expected_result=${test_dir}/compare/${command_id}.sql
+
+	run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+		>$tmp_dir/${command_id}.sql
+	if [ ! -s "$tmp_dir/${command_id}.sql" ]; then
+		sleep 20
+		run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+			>$tmp_dir/${command_id}.sql
+	fi
+	diff -u $expected_result $tmp_dir/${command_id}.sql
+}
+
+run_psql_ssl() {
+	local command="$1"
+	local uri="$2"
+	local driver=${3:-postgres}
+	local suffix=${4:-.svc.cluster.local}
+	local client_container=$(kubectl_bin get pods --selector=name=pg-client -o 'jsonpath={.items[].metadata.name}')
+	local sslmode="$5"
+
+	kubectl_bin exec ${client_container} -- \
+		bash -c "printf '$command\n' | PGSSLMODE=$sslmode PGSSLROOTCERT=/tmp/tls/ca.crt psql -v ON_ERROR_STOP=1 -t -q $driver://$uri$suffix" || true
+}
+
 wait_for_delete() {
 	local res="$1"
 
