Apply suggestions from code review
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -15,23 +15,23 @@ fi
 
 create_namespace() {
 	local namespace=$1
-  if [[ ${CLEAN_NAMESPACE} == 1 ]]; then
-    if [ -n "$OPENSHIFT" ]; then
-      if [ -n "$OPERATOR_NS" -a $(oc get project "$OPERATOR_NS" -o json | jq -r '.metadata.name') ]; then
-        oc delete --grace-period=0 --force=true project "$namespace" && sleep 120 || :
-      else
-        oc delete project "$namespace" && sleep 40 || :
-      fi
-      wait_for_delete "project/$namespace"
+	if [[ ${CLEAN_NAMESPACE} == 1 ]]; then
+		if [ -n "$OPENSHIFT" ]; then
+			if [ -n "$OPERATOR_NS" -a $(oc get project "$OPERATOR_NS" -o json | jq -r '.metadata.name') ]; then
+				oc delete --grace-period=0 --force=true project "$namespace" && sleep 120 || :
+			else
+				oc delete project "$namespace" && sleep 40 || :
+			fi
+			wait_for_delete "project/$namespace"
 
-      desc "create namespace $namespace"
-      oc new-project "$namespace"
-      oc project "$namespace"
-      oc adm policy add-scc-to-user hostaccess -z default || :
-    else:
-      kubectl delete namespace $namespace --ignore-not-found || :
-		  kubectl wait --for=delete namespace "$namespace" || :
-    fi
+			desc "create namespace $namespace"
+			oc new-project "$namespace"
+			oc project "$namespace"
+			oc adm policy add-scc-to-user hostaccess -z default || :
+			else:
+			kubectl delete namespace $namespace --ignore-not-found || :
+			kubectl wait --for=delete namespace "$namespace" || :
+		fi
 	fi
 
 	kubectl create namespace $namespace
@@ -259,34 +259,34 @@ wait_for_delete() {
 }
 
 deploy_pmm_server() {
-  local platform=kubernetes
-  helm uninstall -n "${NAMESPACE}" pmm || :
-  if [ ! -z "$OPENSHIFT" ]; then
-    platform=openshift
-    oc create sa pmm-server -n "${NAMESPACE}"
-    oc adm policy add-scc-to-user privileged -z pmm-server -n "${NAMESPACE}"
-    if [ -n "$OPERATOR_NS" ]; then
-      timeout 30 oc delete clusterrolebinding $(kubectl get clusterrolebinding | grep 'pmm-pg-operator-' | awk '{print $1}') || :
-      oc create clusterrolebinding pmm-pg-operator-cluster-wide --clusterrole=percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
-      oc patch clusterrole/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' ${OPERATOR_NS:+-n $OPERATOR_NS}
-    else
-      oc create rolebinding pmm-pg-operator-namespace-only --role percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
-      oc patch role/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' -n "${NAMESPACE}"
-    fi
-    retry 10 60 helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform --set sa=pmm-server --set supresshttp2=false https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
-  else
-    helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
-  fi
-  SERVICE="postgres"
-  until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
-    echo "Retry $retry"
-    sleep 5
-    let retry+=1
-    if [ $retry -ge 20 ]; then
-      echo "Max retry count $retry reached. Pmm-server can't start"
-      exit 1
-    fi
-  done
+	local platform=kubernetes
+	helm uninstall -n "${NAMESPACE}" pmm || :
+	if [ ! -z "$OPENSHIFT" ]; then
+		platform=openshift
+		oc create sa pmm-server -n "${NAMESPACE}"
+		oc adm policy add-scc-to-user privileged -z pmm-server -n "${NAMESPACE}"
+		if [ -n "$OPERATOR_NS" ]; then
+			timeout 30 oc delete clusterrolebinding $(kubectl get clusterrolebinding | grep 'pmm-pg-operator-' | awk '{print $1}') || :
+			oc create clusterrolebinding pmm-pg-operator-cluster-wide --clusterrole=percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+			oc patch clusterrole/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' ${OPERATOR_NS:+-n $OPERATOR_NS}
+		else
+			oc create rolebinding pmm-pg-operator-namespace-only --role percona-postgresql-operator --serviceaccount=$NAMESPACE:pmm-server -n "${NAMESPACE}"
+			oc patch role/percona-postgresql-operator --type json -p='[{"op":"add","path": "/rules/-","value":{"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"verbs":["use"],"resourceNames":["privileged"]}}]' -n "${NAMESPACE}"
+		fi
+		retry 10 60 helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform --set sa=pmm-server --set supresshttp2=false https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
+	else
+		helm install monitoring --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} --set platform=$platform https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz -n "${NAMESPACE}"
+	fi
+	SERVICE="postgres"
+	until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
+		echo "Retry $retry"
+		sleep 5
+		let retry+=1
+		if [ $retry -ge 20 ]; then
+			echo "Max retry count $retry reached. Pmm-server can't start"
+			exit 1
+		fi
+	done
 }
 
 generate_pmm_api_key() {
@@ -368,7 +368,7 @@ destroy_chaos_mesh() {
 		helm uninstall chaos-mesh --namespace ${chaos_mesh_ns} || :
 	fi
 	timeout 30 kubectl delete crd $(kubectl get crd | grep 'chaos-mesh.org' | awk '{print $1}') || :
-	timeout 30 kubectl  delete clusterrolebinding $(kubectl get clusterrolebinding -n {NAMESPACE}| grep 'chaos-mesh' | awk '{print $1}') || :
+	timeout 30 kubectl delete clusterrolebinding $(kubectl get clusterrolebinding -n {NAMESPACE} | grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete clusterrole $(kubectl get clusterrole | grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete MutatingWebhookConfiguration $(kubectl get MutatingWebhookConfiguration | grep 'chaos-mesh' | awk '{print $1}') || :
 	timeout 30 kubectl delete ValidatingWebhookConfiguration $(kubectl get ValidatingWebhookConfiguration | grep 'chaos-mesh' | awk '{print $1}') || :
