K8SPG-38 Upgrade cluster test (#127)
* K8SPG-38 Simple upgrade test

* K8SPG-38 Draft version of test

* K8SPG-38 Update pcluster and pgreplicas image

* K8SPG-38 Upgrade tls part

* K8SPG-38 Update shared repo image, small fixes

* K8SPG-38 Linter suggestions

* K8SPG-38 Upgrade test candidate

* K8SPG-38 Linter and jenkins suggestions

Co-authored-by: Max Dudin <dudin.mv@gmail.com>

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -111,11 +111,13 @@ desc() {
 }
 
 deploy_operator() {
-	desc 'start operator'
 	local pull_secret_name=${1}
+	local operator_manifest=${2:-"${src_dir}/deploy/operator.yaml"}
+
+	desc 'start operator'
 
 	# modifing ini structure from configMap
-	yq r -d'2' ${src_dir}/deploy/operator.yaml 'data[values.yaml]' \
+	yq r -d'2' "${operator_manifest}" 'data[values.yaml]' \
 		| $sed -e "s#namespace: .*#namespace: \"${namespace}\"#g" \
 		| $sed -e "s#pgo_operator_namespace: .*#pgo_operator_namespace: \"${namespace}\"#g" \
 		| $sed -e "s#pgo_image_tag: .*#pgo_image_tag: $(echo ${IMAGE_OPERATOR%-postgres-operator} | cut -d: -f2)#g" \
@@ -133,7 +135,7 @@ deploy_operator() {
 	fi
 
 	# updating yaml itself
-	yq w -d'*' ${src_dir}/deploy/operator.yaml 'metadata.namespace' ${namespace} \
+	yq w -d'*' "${operator_manifest}" 'metadata.namespace' ${namespace} \
 		| yq w -d'3' - 'subjects[0].namespace' ${namespace} \
 		| yq w -d'4' - 'spec.template.spec.containers[0].image' ${IMAGE_DEPLOYER} \
 		| yq w -d'2' - -d2 'data[values.yaml]' "$(cat ${tmp_dir}/operator.ini)" \
@@ -616,11 +618,18 @@ create_user_secrets() {
 
 wait_cluster_consistency() {
 	cluster_name=${1}
+
+	wait_cluster_status ${cluster_name} "pgcluster Initialized"
+}
+
+wait_cluster_status() {
+	cluster_name=${1}
+	target_status=${2}
 	retry=0
 
-	until [[ "$(kubectl_bin get Pgcluster "${cluster_name}" -o jsonpath='{.status.state}')" == "pgcluster Initialized" ]]; do
+	until [[ "$(kubectl_bin get Pgcluster "${cluster_name}" -o jsonpath='{.status.state}')" == "${target_status}" ]]; do
 		let retry+=1
-		if [ $retry -ge 16 ]; then
+		if [ $retry -ge 24 ]; then
 			echo max retry count $retry reached. something went wrong with operator or kubernetes cluster
 			exit 1
 		fi
@@ -652,6 +661,36 @@ compare_psql_cmd() {
 			>$tmp_dir/${command_id}.sql
 	fi
 	diff -u $expected_result $tmp_dir/${command_id}.sql
+}
+
+compare_psql() {
+	local command_id="$1"
+	local command="$2"
+	local uri="$3"
+	local sslmode="$4"
+
+	local expected_result=${test_dir}/compare/${command_id}.sql
+
+	run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+		>$tmp_dir/${command_id}.sql
+	if [ ! -s "$tmp_dir/${command_id}.sql" ]; then
+		sleep 20
+		run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+			>$tmp_dir/${command_id}.sql
+	fi
+	diff -u $expected_result $tmp_dir/${command_id}.sql
+}
+
+run_psql_ssl() {
+	local command="$1"
+	local uri="$2"
+	local driver=${3:-postgres}
+	local suffix=${4:-.svc.cluster.local}
+	local client_container=$(kubectl_bin get pods --selector=name=pg-client -o 'jsonpath={.items[].metadata.name}')
+	local sslmode="$5"
+
+	kubectl_bin exec ${client_container} -- \
+		bash -c "printf '$command\n' | PGSSLMODE=$sslmode PGSSLROOTCERT=/tmp/tls/ca.crt psql -v ON_ERROR_STOP=1 -t -q $driver://$uri$suffix" || true
 }
 
 wait_for_delete() {
@@ -902,4 +941,34 @@ network_loss() {
 		| yq w - "metadata.namespace" "$namespace" \
 		| yq w - "spec.selector.pods.$namespace[0]" "$pod" \
 		| kubectl_bin apply -f -
+}
+
+compare_psql() {
+	local command_id="$1"
+	local command="$2"
+	local uri="$3"
+	local sslmode="$4"
+
+	local expected_result=${test_dir}/compare/${command_id}.sql
+
+	run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+		>$tmp_dir/${command_id}.sql
+	if [ ! -s "$tmp_dir/${command_id}.sql" ]; then
+		sleep 20
+		run_psql_ssl "$command" "$uri" "postgres" "" "$sslmode" \
+			>$tmp_dir/${command_id}.sql
+	fi
+	diff -u $expected_result $tmp_dir/${command_id}.sql
+}
+
+run_psql_ssl() {
+	local command="$1"
+	local uri="$2"
+	local driver=${3:-postgres}
+	local suffix=${4:-.svc.cluster.local}
+	local client_container=$(kubectl_bin get pods --selector=name=pg-client -o 'jsonpath={.items[].metadata.name}')
+	local sslmode="$5"
+
+	kubectl_bin exec ${client_container} -- \
+		bash -c "printf '$command\n' | PGSSLMODE=$sslmode PGSSLROOTCERT=/tmp/tls/ca.crt psql -v ON_ERROR_STOP=1 -t -q $driver://$uri$suffix" || true
 }
