CLOUD-812 - Fix sporadic failure of monitoring test

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -265,9 +265,18 @@ get_metric_values() {
 	local end=$($date -u "+%s")
 	local endpoint=$(get_service_ip monitoring-service)
 
-	curl -s -k -H "Authorization: Bearer ${api_key}" "https://$endpoint/graph/api/datasources/proxy/1/api/v1/query_range?query=min%28$metric%7Bnode_name%3D%7E%22$instance%22%7d%20or%20$metric%7Bnode_name%3D%7E%22$instance%22%7D%29&start=$start&end=$end&step=60" \
-		| jq '.data.result[0].values[][1]' \
-		| grep '^"[0-9]'
+	set +o xtrace
+	retry=0
+	echo -n $name
+	until [ $(curl -s -k -H "Authorization: Bearer ${api_key}" "https://$endpoint/graph/api/datasources/proxy/1/api/v1/query_range?query=min%28$metric%7Bnode_name%3D%7E%22$instance%22%7d%20or%20$metric%7Bnode_name%3D%7E%22$instance%22%7D%29&start=$start&end=$end&step=60" | jq '.data.result[0].values[][1]' | grep '^"[0-9]') ]; do
+		sleep 5
+		echo -n .
+		let retry+=1
+		if [ $retry -ge 60 ]; then
+			echo "max retry count $retry reached. metrics are missing, something is wrong!"
+			exit 1
+		fi
+	done
 }
 
 get_qan20_values() {
