Merge upstream (#309)
* Merge upstream

* fix CVEs

* remove docs and github templates

* remove crunchy github actions

diff --git a/testing/kuttl/e2e/exporter/01--check-exporter.yaml b/testing/kuttl/e2e/exporter/01--check-exporter.yaml
--- a/testing/kuttl/e2e/exporter/01--check-exporter.yaml
+++ b/testing/kuttl/e2e/exporter/01--check-exporter.yaml
@@ -2,20 +2,45 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
-  # Ensure that the metrics endpoint is available from inside the exporter container
   - script: |
-      name=$(kubectl -n ${NAMESPACE} get pods --no-headers -o custom-columns="name:{metadata.name}" \
-        --selector='postgres-operator.crunchydata.com/cluster=exporter,postgres-operator.crunchydata.com/instance-set=instance1')
-      kubectl -n ${NAMESPACE} exec $name -it -c exporter -- curl http://localhost:9187/metrics
-  # Ensure that the ccp_monitoring user exists in the database
-  - script: |
-      name=$(kubectl -n ${NAMESPACE} get pods --no-headers -o custom-columns="name:{metadata.name}" \
-        --selector='postgres-operator.crunchydata.com/cluster=exporter,postgres-operator.crunchydata.com/instance-set=instance1')
-      kubectl -n ${NAMESPACE} exec $name -it -c database -- \
-        psql -c "DO \$\$
+      set -e
+      PRIMARY=$(
+        kubectl get pod --namespace "${NAMESPACE}" \
+          --output name --selector '
+            postgres-operator.crunchydata.com/cluster=exporter,
+            postgres-operator.crunchydata.com/role=master'
+      )
+
+      # Ensure that the metrics endpoint is available from inside the exporter container
+      {
+        METRICS=$(kubectl exec --namespace "${NAMESPACE}" \
+          "${PRIMARY}" -c exporter \
+          -- curl http://localhost:9187/metrics)
+      } || {
+        echo >&2 'curl metrics endpoint returned error'
+        echo "${METRICS}"
+        exit 1
+      }
+
+      LOGS=$(kubectl logs --namespace "${NAMESPACE}" "${PRIMARY}" -c exporter)
+      contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }
+      {
+        contains "${LOGS}" 'TLS is disabled'
+      } || {
+        echo >&2 'tls is enabled'
+        echo "${LOGS}"
+        exit 1
+      }
+
+      # Ensure that the monitoring user exists and is configured.
+      kubectl exec --stdin --namespace "${NAMESPACE}" "${PRIMARY}" -c database \
+        -- psql -qb --set ON_ERROR_STOP=1 --file=- <<'SQL'
+        DO $$
         DECLARE
-          result boolean;
+          result record;
         BEGIN
-          SELECT 1 from pg_roles where rolname='ccp_monitoring' INTO result;
-          ASSERT result = 't', 'ccp_monitor not found';
-        END \$\$;"
+          SELECT * INTO result FROM pg_catalog.pg_roles WHERE rolname = 'ccp_monitoring';
+          ASSERT FOUND, 'user not found';
+          ASSERT result.rolconfig @> '{jit=off}', format('got config: %L', result.rolconfig);
+        END $$
+      SQL
