K8SPG-786 add upgrade tests and fix K8SPG-1040

diff --git a/e2e-tests/tests/upgrade-minor/09-upgrade-cluster.yaml b/e2e-tests/tests/upgrade-minor/09-upgrade-cluster.yaml
--- a/e2e-tests/tests/upgrade-minor/09-upgrade-cluster.yaml
+++ b/e2e-tests/tests/upgrade-minor/09-upgrade-cluster.yaml
@@ -1,11 +1,19 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
+timeout: 420
 commands:
   - script: |-
       set -o errexit
       set -o xtrace
 
       source ../../functions
+
+      uri="postgres:$(get_psql_user_pass ${test_name}-pguser-postgres)@$(get_psql_user_host ${test_name}-pguser-postgres)"
+      data=$(run_psql_local '\c myapp \\\ SELECT id from myApp ORDER BY id' "$uri" | tr -d '[:space:]')
+      if [[ "$data" != "100500" ]]; then
+          echo "ERROR: unexpected data after restore: '$data' (want only 100500)"
+          exit 1
+      fi
 
       pg_ver_lower="$(cat ${TEMP_DIR}/pg_ver.txt)"
       target_image_postgresql=$IMAGE_POSTGRESQL
@@ -14,25 +22,23 @@ commands:
 
       if [ "$pg_ver_lower" != "$PG_VER" ]; then
           target_image_postgresql="${REGISTRY_NAME_FULL}perconalab/percona-postgresql-operator:main-ppg$pg_ver_lower-postgres"
-          target_image_pgbouncer="${REGISTRY_NAME_FULL}perconalab/percona-postgresql-operator:main-ppg$pg_ver_lower-pgbouncer"
-          target_image_backrest="${REGISTRY_NAME_FULL}perconalab/percona-postgresql-operator:main-ppg$pg_ver_lower-pgbackrest"
+          target_image_pgbouncer="${REGISTRY_NAME_FULL}perconalab/percona-postgresql-operator:main-pgbouncer$pg_ver_lower"
+          target_image_backrest="${REGISTRY_NAME_FULL}perconalab/percona-postgresql-operator:main-pgbackrest$pg_ver_lower"
       fi
       cr_ver=$(yq '.spec.crVersion' $DEPLOY_DIR/cr.yaml)
 
       yq -i eval '
-          .metadata.name = "'${test_name}'" |
-          .metadata.labels = {"e2e":"'${test_name}'"} |
           .spec.crVersion = "'${cr_ver}'" |
+          .spec.initContainer.image = "'${IMAGE}'" |
           .spec.image = "'${target_image_postgresql}'" |
           .spec.proxy.pgBouncer.image = "'${target_image_pgbouncer}'" |
-          .spec.backups.pgbackrest.image = "'${target_image_backrest}'"' "${TEMP_DIR}/cr_lower.yaml"
-      kubectl -n "${NAMESPACE}" apply -f "${TEMP_DIR}/cr_lower.yaml"
+          .spec.backups.pgbackrest.image = "'${target_image_backrest}'"' "${TEMP_DIR}/cr.yaml"
+      kubectl -n "${NAMESPACE}" apply -f "${TEMP_DIR}/cr.yaml"
       sleep 7 # wait for reconcile loop
 
       kubectl wait -n $NAMESPACE --timeout 180s --for=jsonpath='{.spec.template.spec.containers[0].image}'=$target_image_backrest sts/upgrade-minor-repo-host
       kubectl wait -n $NAMESPACE --timeout 180s --for=jsonpath='{.spec.template.spec.containers[0].image}'=$target_image_pgbouncer deployment/upgrade-minor-pgbouncer
       for s in $(kubectl get sts -n $NAMESPACE --no-headers -l postgres-operator.crunchydata.com/instance-set=instance1 --output=custom-columns='NAME:.metadata.name'); do
-          kubectl wait -n $NAMESPACE --timeout 180s --for=jsonpath='{.spec.template.spec.containers[0].image}'=$target_image_postgresql sts/${s}
+          kubectl wait -n $NAMESPACE --timeout 300s --for=jsonpath='{.spec.template.spec.containers[?(@.name=="database")].image}'=$target_image_postgresql sts/${s}
       done
-    timeout: 180
-
+      wait_cluster_consistency ${test_name}
